default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "" } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "happyhour_api_development" } %>

test:
  <<: *default
  database: appyhour_api_test

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_PROD") { "happyhour_api_production" } %>
  username: <%= ENV.fetch("DB_USERNAME_PROD") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD_PROD") { "" } %>
  host: <%= ENV.fetch("DB_HOST_PROD") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT_PROD") { 5432 } %>
